#
# The channel resolution: pure functions from a list of selected catalogue entries to the
# per-plane outputs a backend consumes. No module system, no `pkgs`, no `config` -- so
# `../checks/default.nix` can drive every branch with fixture tables containing entry shapes the
# real catalogue does not happen to have today.
#
# WHY THAT SEPARATION IS NOT DECORATION, the same reasoning the sibling nixfs/nixoffice versions
# of this file give: the real catalogue in ./toolchain.nix has no `aur = true` row and no
# `arch = null` row, so `archPackages`/`aurPackages` and `nixpkgsPackages`/`unavailableOnArch`
# return identical results against it whether their splits work or are no-ops. A test that can
# only reach these functions THROUGH the real catalogue therefore cannot tell a working split from
# a broken one -- and the failure mode is not subtle: `pacman -S` handed an AUR name fails the
# whole transaction on "target not found", taking every other package in the same converge down
# with it.
#
# THE ANTI-SHADOWING INVARIANT LIVES IN THESE FOUR FUNCTIONS, and it has a different shape on each
# plane:
#
#   Arch  -- `archPackages ++ aurPackages` covers every entry that HAS a pacman name, and
#            `unavailableOnArch` is the disjoint remainder that the Arch backend may install from
#            nixpkgs. No entry is ever in both, so no tool is ever installed twice.
#   NixOS -- `nixpkgsPackages` excludes `viaLibvirtd` rows, because `virtualisation.libvirtd`
#            already delivers those and the QEMU it EXECS is the one named by
#            `virtualisation.libvirtd.qemu.package`. A second copy in `environment.systemPackages`
#            would be a differently-configured binary nothing ever runs.
{ lib }:
rec {
  # Official-repo pacman names. `aur = true` entries are held back for `aurPackages` below.
  archPackages = selected:
    lib.unique (map (t: t.arch)
      (lib.filter (t: (t.arch or null) != null && !(t.aur or false)) selected));

  aurPackages = selected:
    lib.unique (map (t: t.arch)
      (lib.filter (t: (t.arch or null) != null && (t.aur or false)) selected));

  # Entries with no Arch package at all -- official repo OR AUR. These are the ONLY ones an Arch
  # host may install from nixpkgs, because they are the only ones where no distro copy exists to
  # shadow or be shadowed by. Gated on the missing `arch` field and nothing else: which other
  # channels an entry happens to carry says nothing about whether Arch can install it.
  unavailableOnArch = selected:
    lib.unique (map (t: t.name) (lib.filter (t: (t.arch or null) == null) selected));

  # The nixpkgs attribute names the NixOS backend puts in `environment.systemPackages`.
  #
  # TWO exclusions, and they mean opposite things. `nixpkgs == null` is an entry nixpkgs has no
  # package for at all (every `architectures` row). `viaLibvirtd` is an entry nixpkgs DOES have and
  # that NixOS must nevertheless not install this way, because `virtualisation.libvirtd` is
  # already delivering it -- see this file's header.
  nixpkgsPackages = selected:
    lib.unique (map (t: t.nixpkgs)
      (lib.filter (t: (t.nixpkgs or null) != null && !(t.viaLibvirtd or false)) selected));

  # The `--target-list=` QEMU is configured with, de-duplicated: several catalogue keys can
  # legitimately name the same target, and the native targets are always present regardless of
  # what was selected.
  qemuTargets = nativeTargets: selected:
    lib.unique (nativeTargets ++ lib.concatMap (a: a.qemuTargets or [ ]) selected);

  # ── Remote libvirtd connections ─────────────────────────────────────────────────────────────
  #
  # Rendered as libvirt's own `uri_aliases`, which is the ONE mechanism that makes a remote
  # reachable by every client at once -- `virsh -c server`, `virt-manager`, `virt-viewer` -- from
  # a single declaration, rather than each application storing its own copy of the same string in
  # its own settings store.
  #
  # WHERE the resulting file goes is a per-plane fact and deliberately not decided here: libvirt
  # reads it from the `sysconfdir` it was BUILT with, and the two planes disagree. A distro
  # libvirt is built with `--sysconfdir=/etc` (so `/etc/libvirt/libvirt.conf`); nixpkgs builds it
  # with `--sysconfdir=/var/lib` (so `/var/lib/libvirt/libvirt.conf`, which is also why the NixOS
  # libvirtd module copies its generated `qemu.conf` there rather than into `/etc`). Each backend
  # supplies its own path; this function only produces the text.
  aliasFileText = remotes:
    let
      names = lib.attrNames remotes;
      line = name: "  \"${name}=${remotes.${name}.uri}\",";
    in
    ''
      # Generated by nixvm -- do not edit. Declared in nixvm.host.remotes.
      uri_aliases = [
      ${lib.concatStringsSep "\n" (map line names)}
      ]
    '';

  # libvirt resolves an alias by scanning for the first character outside this set and treating
  # everything before it as the name, so a name containing anything else does not fail loudly --
  # it silently matches a PREFIX of itself, or nothing, and the operator is left with a URI that
  # "does not work" and no error to search for. Fail at eval instead.
  aliasNameOk = name: (builtins.match "[a-zA-Z0-9_-]+" name) != null;

  # A `"` would close the string libvirt is parsing and a newline would end the entry, so either
  # one turns a declared URI into a syntactically different file. Neither can appear in a legal
  # libvirt connection URI, so rejecting them costs nothing real.
  uriOk = uri: (builtins.match ''.*["${"\n"}].*'' uri) == null;
}
