#
# The channel resolution: pure functions from a selection to the per-plane outputs a backend
# consumes. No module system, no `pkgs`, no `config` -- so `../checks/default.nix` can drive
# every branch with fixture tables containing entry shapes the real catalogue does not happen to
# have today.
#
# WHY THAT SEPARATION IS NOT DECORATION. The real catalogue in ./toolchain.nix has no AUR entry
# in it, so `archPackages` and `aurPackages` return exactly the same thing against it whether the
# AUR split works or is a no-op. A test that can only reach these functions THROUGH the real
# catalogue therefore cannot tell a working split from a broken one -- and the failure mode of a
# broken one is not subtle: `pacman -S` handed an AUR name fails the whole transaction on "target
# not found", taking every other package in the same converge down with it. The fixtures in
# `checks/default.nix` are the inputs that distinguish them.
{ lib }:
rec {
  # Official-repo pacman names. `aur = true` entries are held back for `aurPackages` below.
  archPackages = entries:
    lib.unique (map (t: t.arch)
      (lib.filter (t: (t.arch or null) != null && !(t.aur or false)) entries));

  aurPackages = entries:
    lib.unique (map (t: t.arch)
      (lib.filter (t: (t.arch or null) != null && (t.aur or false)) entries));

  # nixpkgs attribute paths. A `null` here is a POSITIVE statement -- "the NixOS plane gets this
  # from `virtualisation.libvirtd` rather than from a package list" -- see ./toolchain.nix's own
  # header. Dropping it silently is therefore correct, unlike a null pacman name, which would be
  # a genuine catalogue defect and is checked for separately.
  nixpkgsNames = entries:
    lib.unique (map (t: t.nixpkgs)
      (lib.filter (t: (t.nixpkgs or null) != null) entries));

  # The `--target-list=` QEMU is configured with, de-duplicated: several catalogue keys can
  # legitimately name the same target (and the native targets are always present regardless of
  # what was selected).
  qemuTargets = nativeTargets: entries:
    lib.unique (nativeTargets ++ lib.concatMap (a: a.qemuTargets) entries);

  # ── Remote libvirtd connections ─────────────────────────────────────────────────────────────
  #
  # Rendered as libvirt's own `uri_aliases`, which is the ONE mechanism that makes a remote
  # reachable by every client at once -- `virsh -c server`, `virt-manager`, `virt-viewer` -- from
  # a single declaration, rather than each application storing its own copy of the same string in
  # its own settings store.
  #
  # WHERE the resulting file goes is a per-plane fact and deliberately not decided here: libvirt
  # reads it from the `sysconfdir` it was BUILT with, and the two planes disagree. A distro
  # libvirt is built with `--sysconfdir=/etc` (so `/etc/libvirt/libvirt.conf`); nixpkgs builds it
  # with `--sysconfdir=/var/lib` (so `/var/lib/libvirt/libvirt.conf`, which is also why the NixOS
  # libvirtd module copies its generated `qemu.conf` there rather than into `/etc`). Each backend
  # supplies its own path; this function only produces the text.
  aliasFileText = remotes:
    let
      names = lib.attrNames remotes;
      line = name: "  \"${name}=${remotes.${name}.uri}\",";
    in
    ''
      # Generated by nixvm -- do not edit. Declared in nixvm.host.remotes.
      uri_aliases = [
      ${lib.concatStringsSep "\n" (map line names)}
      ]
    '';

  # libvirt resolves an alias by scanning for the first character outside this set and treating
  # everything before it as the name, so a name containing anything else does not fail loudly --
  # it silently matches a PREFIX of itself, or nothing, and the operator is left with a URI that
  # "does not work" and no error to search for. Fail at eval instead.
  aliasNameOk = name: (builtins.match "[a-zA-Z0-9_-]+" name) != null;

  # A `"` would close the string libvirt is parsing and a newline would end the entry, so either
  # one turns a declared URI into a syntactically different file. Neither can appear in a legal
  # libvirt connection URI, so rejecting them costs nothing real.
  uriOk = uri: (builtins.match ''.*["${"\n"}].*'' uri) == null;
}
